### PR TITLE
Added two scripts for print & hive nightmare. replaced a 404 link to owasp

### PR DESCRIPTION
**Pull request by Burns-Sleep**
Hey, this is destriant | nreave3!

### CODE REVIEW

**Review by Ednas — CHANGES_REQUESTED** [review]
I see you added Print Nightmare as a header, do you have something to link here, a support article, or an advisory? Or can you provide some information directly here about Patches for this issue?

**Review by Ednas — CHANGES_REQUESTED** [review]
Good find, we want to stick with the web version here, so let's use https://cheatsheetseries.owasp.org/ This entire file is a To Do item, so if you want to pull some of tips and helpful bits from the Cheatsheets to add here, and get this started, that would be welcomed.

**Review by Ednas — APPROVED** [review]
Fantastic, this looks great!

**Review by Burns-Sleep — COMMENTED** [review]
Will flesh out the web apps page tomorrow after work, before the deadline. I usually leave work around 2 pm central

**Review by Ednas — APPROVED** [review]

**Pull request merged**
